### ISSUE TITLE
Blacklist Google Poly and Sketchfab item search with blacklist.json

### ISSUE THREAD

**Issue by shawticus** [xrchat/spoke-xrchat-adapter#2]
Current Blacklist

**Comment by igorgark1593** [comment]
blacklist.json formed on the backend? blacklist.json Issued from the backend upon frontend request. The task is to sort the blacklist.json strings in the search string on the frontend and display the result? Will there be a link to the 3D model in blacklist.json?

**Comment by dmitrizagidulin** [comment]
(waiting on Kai to provide the actual blacklist items.)

**Comment by shawticus** [comment]
A good example would be like
drugs
sex
boobs

etc etc -- let's just start with those.

**Comment by dmitrizagidulin** [comment]
@igorgark1593 Specifically, we're blacklisting just the search strings (once search is implemented). There will not be links to blacklisted specific models.

**Comment by dmitrizagidulin** [comment]
Moving to issue https://github.com/xrchat/kxr-dev/issues/19 (closing this one).
