### ISSUE TITLE
Refactor Mozilla Hubs / Reticulum Integration to be an included adapter

### ISSUE THREAD

**Issue by shawticus** [xrchat/spoke-xrchat-adapter#5]
Move the hard coded connections to Reticulum into an adapter to work with the adapter interface

**Comment by igorgark1593** [comment]
The request to give a more detailed answer about Move the hard-coded connections to Reticulum into an adapter to work with the adapter interface. It is not entirely understanding.

**Comment by dmitrizagidulin** [comment]
Merging this issue into #6.
